screenTimeHealth/config/routes.rb
Rails.application.routes.draw do
  

  devise_for :families

  root 'static_pages#index'

  get 'static_pages/home'

  get 'static_pages/about'

  get 'family/view'

  get 'family/edit'

  get 'family/add'

  patch 'family/create_kid'

  get 'kid/view'

  get 'kid/add'

  post 'kid/create'

  get 'kid/delete'

  get 'analytics/start'

  get 'analytics/end'

  get 'analytics/track'

end

screenTimeHealth/app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>"><span><i class="mi" style="padding-right: 10px">restore</i> Screen Time</span></a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <% if family_signed_in? %>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="<%= family_view_path %>">Family</a></li>
      <li><a href="<%= static_pages_about_path %>">About</a></li>
      <li class="dropdown">
        <a href="" data-target="#" class="dropdown-toggle" data-toggle="dropdown">My account <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Edit Account', edit_family_registration_path %></li>
          <li><%= link_to 'Log Out', destroy_family_session_path, :method => :delete %></li>
        </ul>
      </li>
    </ul>
    <% else %>

        <ul class="nav navbar-nav navbar-right">
      <li><a href="<%= static_pages_about_path %>">About</a></li>
      <li class="dropdown">
        <a href="" data-target="#" class="dropdown-toggle" data-toggle="dropdown">My account <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Sign Up', new_family_registration_path %></li>
          <li><%= link_to 'Log In', new_family_session_path %></li>
        </ul>
      </li>
    </ul>

<% end %>

  </div>
</div>

screenTimeHealth/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>ScreenTimeHealth</title>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <%= render 'layouts/navbar' %>
    <div style="background:#4caf50;">
      <div class="container">
      <% if notice %>
        <div class="alert alert-info"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-warning"><%= alert %></div>
      <% end %>
    </div>
    </div>
    <div class="container">
      <%= yield %>
    </div>
    <%= include_gon %>
  </body>
</html>