screenTimeHealth/config/routes.rb
Rails.application.routes.draw do
  

  devise_for :families

  root 'static_pages#index'

  get 'static_pages/home'

  get 'static_pages/about'

  get 'family/view'

  get 'family/edit'

  get 'family/add'

  patch 'family/create_kid'

  get 'kid/view'

  get 'kid/add'

  post 'kid/create'

  get 'kid/delete'

  get 'analytics/start'

  get 'analytics/end'

  get 'analytics/track'

end

screenTimeHealth/app/models/family.rb
class Family < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  
  has_many :kids
  accepts_nested_attributes_for :kids, :allow_destroy => true


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true
  validates :surname, presence: true
  validates :password, presence: true

end

screenTimeHealth/app/controllers/family_controller.rb
class FamilyController < ApplicationController

  def view
    @family = current_family
    @kids = current_family.kids
    @last_kid_session = {}

    @kids.each do |k|
      if(k.session.count != 0)
      sessions = k.session.where("DATE(starttime) = ?", Date.today)
      total = 0
      sessions.each do |s|
        if session.endtime.nil?
        total += ((s.endtime - s.starttime) / 60)
      end
      end

      @last_kid_session[k.id] = total.to_i
      end
    end

    
  end

  def edit
    @family = current_family
    @family_name = @family.surname
  end

  def add

  end

  def family_params
    params.require(:family).permit(:id, :email, :surname, kids_attributes: [:id, :name, :_destroy])
  end


end

screenTimeHealth/app/helpers/family_helper.rb
module FamilyHelper
end

screenTimeHealth/app/views/family/add.html.erb
<div class="row">
<h1>Add family member</h1>
</div>
<section>
  <%= form_tag({controller: "kid", action: "create"}, :id => "", :class => "form-horizonal") do %>
    <%= label_tag :name, 'Name', :class => "control-label" %>
    <%= text_field_tag :name, '',:class => "form-control" %>
    <%= label_tag :threshold, 'Threshold for critical amount of time in front of screen (in minutes)', :class => "control-label" %>
    <%= text_field_tag :threshold, '',:class => "form-control" %>
    <%= submit_tag "Add", :class => "btn btn-lg btn-primary" %>
  <% end %>
  
</section>

screenTimeHealth/app/views/family/edit.html.erb
<div class="container">
<div class="row">
<p>Family name: <%= @family_name %></p>
</div>
<div class="row">

    <%= nested_form_for @family, :url => family_create_kid_path do |f| %>
        <fieldset>
          <%= f.fields_for :kids do |kid_form| %>
          <%= kid_form.text_field :name %>
          <%= kid_form.link_to_remove "Remove kid" %>
          <% end %>
        <%= f.link_to_add "Add Family Member", :kids, :class => 'btn btn-primary btn-sm btn-block' %>
    </fieldset>

      <div class="row text-center">
        <div class="legal-document-actions">
              <%= f.submit "Save changes", :class => "btn btn-lg btn-primary" %>
          </div>
        <% end %>
      </div>
</div>

<div class="row">


</div>

</div>

screenTimeHealth/app/views/family/view.html.erb
<div class="container">
	<div class="row">
		<h2><%= @family.surname %></h2>
	</div>
  <div class="row">
    <%= link_to 'Add', family_add_path, :class => 'btn btn-primary btn-lg' %>
  </div>
  <div class="row">
    <h3> Number of kids: <%= @kids.count %> </h3>
  </div>
  <div class="row">
    <% @kids.each do |kid, index| %>
      <div class="col-md-4">
        <a href="/kid/view?id=<%= kid.id %>" type="button"> 
          <div class="panel">
              <div class="panel-heading">
                  <h3 class="panel-title"><%= kid.name %></h3>
              </div>
              <div class="panel-body">
                <div class="text-center">
                  <input type="text" value="<%= @last_kid_session[kid.id] > kid.threshold / 60 ? kid.threshold / 60 : @last_kid_session[kid.id] %>" data-max="<%= kid.threshold / 60 %>" class="dial">
                </div>
              </div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
</div>